# Generated by Django 4.2.21 on 2025-05-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='exercises',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='image',
            name='problems',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
